USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lenovo/lifetab_e10310/BoardConfigVendor.mk

LOCAL_PATH := /home/julius/Development/Porting-Lifetab/phablet/device/lenovo/lifetab_e10310

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := rk3066
TARGET_BOARD_HARDWARE := rk30board
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := rk30board

BOARD_KERNEL_CMDLINE :=
BOARD_MKBOOTIMG_ARGS := --ramdiskaddr 0x62000000 --secondaddr 60f00000 --tagsaddr 60088000
BOARD_KERNEL_BASE := 0x60400000
BOARD_KERNEL_PAGESIZE := 16384

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
#TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 14730395648
BOARD_CACHEIMAGE_PARTITION_SIZE := 536870912
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_KERNEL_SOURCE := kernel/lenovo/lifetab_e10310
TARGET_KERNEL_CONFIG := lifetab_e10310_defconfig
TARGET_USES_UNCOMPRESSED_KERNEL := true
TARGET_PREBUILT_KERNEL := device/lenovo/lifetab_e10310/kernel

TARGET_RECOVERY_FSTAB := device/lenovo/lifetab_e10310/fstab-recovery.rk30board
#DEVICE_RESOLUTION = 1280*800
PRODUCT_CHARACTERISTICS := tablet

BOARD_EGL_CONFIG := device/lenovo/lifetab_e10310/egl.cfg

BOARD_USE_SKIA_LCDTEXT := true
BOARD_HAVE_VPU := true
#USE_OPENGL_RENDERER := true
#BOARD_NEEDS_MEMORYHEAPPMEM := true
#BOARD_EGL_NEEDS_LEGACY_FB := true
TARGET_USES_ION := true

BOARD_USES_HWCOMPOSER := true

BOARD_HAS_NO_SELECT_BUTTON := true

#TARGET_KERNEL_UBUNTU_META := linux-image-rk30board
TARGET_KERNEL_UBUNTU_SERIES := wily
TARGET_RECOVERY_SKIP_GPG_VERIFICATION := true

#INIT_BOOTCHART := true

BOARD_OVERLAY_INITRD := true